lavanda_usuario:
    resource: "@LavandaBundle/Resources/config/routing/usuario.yml"
    prefix: /

lavanda_servicio:
    resource: "@LavandaBundle/Resources/config/routing/servicio.yml"
    prefix: /

lavanda_empleado:
    resource: "@LavandaBundle/Resources/config/routing/empleado.yml"
    prefix: /

lavanda_empresa:
    resource: "@LavandaBundle/Resources/config/routing/empresa.yml"
    prefix: /

lavanda_users:
    resource: "@LavandaBundle/Resources/config/routing/users.yml"
    prefix: /

lavanda_cortesias:
    resource: "@LavandaBundle/Resources/config/routing/cortesia.yml"
    prefix: /

lavanda_productos:
    resource: "@LavandaBundle/Resources/config/routing/producto.yml"
    prefix: /

lavanda_clientes:
    resource: "@LavandaBundle/Resources/config/routing/cliente.yml"
    prefix: /

lavanda_citas:
    resource: "@LavandaBundle/Resources/config/routing/citas.yml"
    prefix: /

lavanda_encuesta:
    resource: "@LavandaBundle/Resources/config/routing/encuesta.yml"
    prefix: /

lavanda_cobranza:
    resource: "@LavandaBundle/Resources/config/routing/cobranza.yml"
    prefix: /

lavanda_sucursal:
    resource: "@LavandaBundle/Resources/config/routing/sucursal.yml"
    prefix: /

lavanda_expediente:
    resource: "@LavandaBundle/Resources/config/routing/expediente.yml"
    prefix: /

lavanda_galeria:
    resource: "@LavandaBundle/Resources/config/routing/galeria.yml"
    prefix: /

lavanda_procesos:
    resource: "@LavandaBundle/Resources/config/routing/proceso.yml"
    prefix: /

lavanda_serviciolongitud:
    resource: "@LavandaBundle/Resources/config/routing/serviciolongitud.yml"
    prefix: /

lavanda_fotosservicio:
    resource: "@LavandaBundle/Resources/config/routing/fotosservicio.yml"
    prefix: /

lavanda_anonimo:
    resource: "@LavandaBundle/Resources/config/routing/anonimos.yml"
    prefix: /

lavanda_proveedores:
    resource: "@LavandaBundle/Resources/config/routing/proveedores.yml"
    prefix: /

lavanda_bodegas:
    resource: "@LavandaBundle/Resources/config/routing/bodegas.yml"
    prefix: /

lavanda_categorias:
    resource: "@LavandaBundle/Resources/config/routing/categorias.yml"
    prefix: /

lavanda_unidadesmedida:
    resource: "@LavandaBundle/Resources/config/routing/unidadesmedida.yml"
    prefix: /

lavanda_compras:
    resource: "@LavandaBundle/Resources/config/routing/compras.yml"
    prefix: /

lavanda_servicioproducto:
    resource: "@LavandaBundle/Resources/config/routing/servicioproducto.yml"
    prefix: /

lavanda_cortesiaproducto:
    resource: "@LavandaBundle/Resources/config/routing/cortesiaproducto.yml"
    prefix: /

lavanda_bar:
    resource: "@LavandaBundle/Resources/config/routing/bar.yml"
    prefix: /

lavanda_barventa:
    resource: "@LavandaBundle/Resources/config/routing/barventa.yml"
    prefix: /

lavanda_detallebarventa:
    resource: "@LavandaBundle/Resources/config/routing/detallebarventa.yml"
    prefix: /

lavanda_formaspago:
    resource: "@LavandaBundle/Resources/config/routing/formaspago.yml"
    prefix: /

lavanda_paquetes:
    resource: "@LavandaBundle/Resources/config/routing/paquetes.yml"
    prefix: /

lavanda_pagospaquetes:
    resource: "@LavandaBundle/Resources/config/routing/pagospaquetes.yml"
    prefix: /