services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
#    lavanda.example:
#        class: LavandaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
