LavandaBundle\Entity\Categorias:
    type: entity
    table: categorias
    id:
        idcategorias:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        descripcion:
            type: string
            nullable: true
            length: 300
            options:
                fixed: false
    lifecycleCallbacks: {  }
