LavandaBundle\Entity\Diagnostico:
    type: entity
    table: diagnostico
    id:
        iddiagnostico:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idDiagnostico
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
