LavandaBundle\Entity\Estatusventa:
    type: entity
    table: estatusventa
    id:
        idestatusventa:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        clave:
            type: string
            nullable: true
            length: 3
            options:
                fixed: true
    lifecycleCallbacks: {  }
