LavandaBundle\Entity\Notificaciones:
    type: entity
    table: notificaciones
    indexes:
        usuario_notificaciones_fk:
            columns:
                - idUsuario
    id:
        idnotificacion:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idNotificacion
            generator:
                strategy: IDENTITY
    fields:
        titulo:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        mensaje:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        fecha:
            type: datetime
            nullable: false
    manyToOne:
        idusuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idUsuario:
                    referencedColumnName: idUsuario
            orphanRemoval: false
    lifecycleCallbacks: {  }
