LavandaBundle\Entity\Producto:
    type: entity
    table: producto
    indexes:
        categoria_producto_fk_idx:
            columns:
                - idcategoria
        bodega_producto_fk_idx:
            columns:
                - idbodega
        unidadmedida_producto_fk_idx:
            columns:
                - unidadmedida
    id:
        idproducto:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idProducto
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 150
            options:
                fixed: false
        descripcion:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        rutaimagen:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: rutaImagen
        nombreimagen:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: nombreImagen
        fechaalta:
            type: date
            nullable: false
            column: fechaAlta
        fechabaja:
            type: date
            nullable: true
            column: fechaBaja
        disponible:
            type: boolean
            nullable: false
        stockmin:
            type: integer
            nullable: true
            options:
                unsigned: false
        stock:
            type: integer
            nullable: true
            options:
                unsigned: false
        inventariocortesia:
            type: boolean
            nullable: true
            column: inventarioCortesia
    manyToOne:
        idbodega:
            targetEntity: Bodegas
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idbodega:
                    referencedColumnName: idbodega
            orphanRemoval: false
        idcategoria:
            targetEntity: Categorias
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcategoria:
                    referencedColumnName: idcategorias
            orphanRemoval: false
        unidadmedida:
            targetEntity: Unidadesmedida
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                unidadmedida:
                    referencedColumnName: idunidadesmedida
            orphanRemoval: false
    lifecycleCallbacks: {  }
