LavandaBundle\Entity\Unidadesmedida:
    type: entity
    table: unidadesmedida
    id:
        idunidadesmedida:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
    lifecycleCallbacks: {  }
