citas_index:
    path: /citas
    defaults: { _controller: LavandaBundle:Citas:index }

citas_listado:
    path: /citas/listado
    defaults: { _controller: LavandaBundle:Citas:buscarCitas }

citas_actualizar_estatus:
    path: /citas/actualizar_estatus
    defaults: { _controller: LavandaBundle:Citas:actualizarEstatusCita }
    condition: "request.isXmlHttpRequest()"

citas_historial:
    path: /citas/historial
    defaults: { _controller: LavandaBundle:Citas:historialCitas }

citas_cobranza:
    path: /citas/cobranza
    defaults: { _controller: LavandaBundle:Cobranza:index }

citas_proceso:
    path: /citas/proceso
    defaults: { _controller: LavandaBundle:Citas:registraCitaProceso }
    condition: "request.isXmlHttpRequest()"

citas_registro:
    path: /citas/registro
    defaults: { _controller: LavandaBundle:Citas:registrarCita }

citas_cliente_index:
    path: /citas/miscitas
    defaults: { _controller: LavandaBundle:Citas:citasClienteIndex }

citas_cliente_listado:
    path: /citas/miscitas/listado
    defaults: { _controller: LavandaBundle:Citas:buscarCitasCliente }
    condition: "request.isXmlHttpRequest()"

citas_cliente_registro:
    path: /citas/miscitas/registro
    defaults: { _controller: LavandaBundle:Citas:registrarCitaCliente }