empleado_index:
    path: /empleados
    defaults: { _controller: "LavandaBundle:Empleado:index"}

empleado_new:
    path: /empleados/new
    defaults: { _controller: "LavandaBundle:Empleado:new"}

empleado_edit:
    path: /empleados/edit/{idempleado}
    defaults: { _controller: "LavandaBundle:Empleado:edit"}

empleado_sucursal:
    path: /empleados/sucursal
    defaults: { _controller: "LavandaBundle:Empleado:listarEmpleadosSucursal"}
    condition: "request.isXmlHttpRequest()"