users_index:
    path: /users
    defaults: { _controller: LavandaBundle:Usuarios:index}

users_registrar_usuario:
    path: /users/registrar_usuario
    defaults: { _controller: LavandaBundle:Usuarios:registrarUsuario}

users_validar_username:
    path: /users/validar_username
    defaults: { _controller: LavandaBundle:Usuarios:validarUsername}
    condition: "request.isXmlHttpRequest()"

users_editar_usuario:
    path: /users/editar_usuario/{idusuario}
    defaults: { _controller: LavandaBundle:Usuarios:editarUsuario}

users_lock_user:
    path: /users/lock_user
    defaults: { _controller: LavandaBundle:Usuarios:lockUser }
    condition: "request.isXmlHttpRequest()"

users_unlock_user:
    path: /users/unlock_user
    defaults: { _controller: LavandaBundle:Usuarios:unlockUser }
    condition: "request.isXmlHttpRequest()"